# -*- coding: utf-8 -*-
import string
import re
import random


class Eliza(object):

	def __init__(self):
		self.keys = map(lambda x: re.compile(x[0], re.IGNORECASE), gPats)
		self.values = map(lambda x: x[1], gPats)

	def translate(self, str, dict):
		words = string.split(string.lower(str))
		keys = dict.keys()
		for i in range(len(words)):
			if words[i] in keys:
				words[i] = dict[words[i]]
		return string.join(words)

	def respond(self, str):
		for i in range(len(self.keys)):
			match = self.keys[i].match(str)
			if match:
				resp = random.choice(self.values[i])
				pos = string.find(resp,'%')
				while pos > -1:
					num = string.atoi(resp[pos+1 : pos+2])
					resp = resp[:pos] + self.translate(match.group(num), gReflections) + resp[pos+2 :]
					pos = string.find(resp,'%')
				if resp[-2:] == '?.': resp = resp[:-2] + '.'
				if resp[-2:] == '??': resp = resp[:-2] + '?'
				return resp

#TILDAR FFT
gReflections = {
	"soy" : "eres",
	"estoy" : "estas",
	"era" : "eras",
	"estaba" : "estabas",
	"fui" : "fuiste",
	"yo" : "tu",
	"seria" : "serias",
	"haria" : "harias",
	"he" : "has",
	"habría" : "habrías",
	"habrías" : "habría",
	"seré" : "seras",
	"estaré" : "estaras",
	"mi" : "tu",
	"eres" : "soy",
	"estas" : "estoy",
	"has" : "he",
	"seras" : "seré",
	"estaras" : "estaré",
	"tu" : "mi",
	"tuyo" : "mio",
	"mio" : "tuyo",
	"ti" : "mi",
	"mi" : "ti",
	# aceptar
	"aceptaré" : "aceptarás",
	"aceptarás" : "aceptaré",
	"acepto" : "aceptas",
	"aceptas" : "acepto",
	"acepté" : "aceptaste",
	"aceptaste" : "acepté",
	"aceptaba" : "aceptabas",
	"aceptabas" : "aceptaba",
	"aceptaría" : "aceptarías",
	"aceptarías" : "aceptaría",
	# permitir
	"permitiré" : "permitirás",
	"permitirás" : "permitiré",
	"permito" : "permites",
	"permites" : "permito",
	"permití" : "permitiste",
	"permitiste" : "permití",
	"permitía" : "permitías",
	"permitías" : "permitía",
	"permitiría" : "permitirías",
	"permitirías" : "permitiría",
	#preguntar
	"preguntaré" : "preguntarás",
	"preguntarás" : "preguntaré",
	"pregunto" : "prenguntas",
	"preguntas" : "preguntas",
	"pregunté" : "preguntaste",
	"preguntaste" : "pregunté",
	"preguntaba" : "preguntabas",
	"preguntabas" : "preguntaba",
	"preguntaría" : "preguntarías",
	"preguntarías" : "preguntaría",
	#creer
	"creeré" : "creerás",
	"creerás" : "creeré",
	"creo" : "crees",
	"crees" : "creo",
	"creí" : "creiste",
	"creiste" : "creí",
	"creía" : "creías",
	"creías" : "creía",
	"creería" : "creerías",
	"creerías" : "creería",
	# prestar
	"prestaré" : "prestarás",
	"prestarás" : "prestaré",
	"presto" : "prestas",
	"prestas" : "presto",
	"presté" : "prestaste",
	"prestaste" : "presté",
	"prestaba" : "prestabas",
	"prestabas" : "prestaba",
	"prestaría" : "prestarías",
	"prestarías" : "prestaría",
	# romper
	"romperé" : "romperás",
	"romperás" : "romperé",
	"rompo" : "rompes",
	"rompes" : "rompo",
	"rompí" : "rompiste",
	"rompiste" : "rompí",
	"rompías" : "rompía",
	"rompía" : "rompías",
	"rompería" : "romperías",
	"romperías" : "rompería",
	#traer
	"traerás" : "traeré",
	"traeré" : "traerás",
	"traigo" : "traes",
	"traes" : "traigo",
	"trajé" : "trajiste",
	"trajiste" : "trajé",
	"traía" : "traías",
	"traías" : "traía",
	"traería" : "traerías",
	"traerías" : "traería",
	#comprar
	"compraré" : "comprarás",
	"comprarás" : "compraré",
	"compro" : "compras",
	"compras" : "compro",
	"compré" : "compraste",
	"compraste" : "compré",
	"compraba" : "comprabas",
	"comprabas" : "compraba",
	"comprarías" : "compraría",
	"compraría" : "comprarías",
	# tener
	"tendré" : "tendrás",
	"tendrás" : "tendré",
	"tengo" : "tienes",
	"tienes" : "tengo",
	"tuve" : "tuviste",
	"tuviste" : "tuve",
	"tenía" : "tenías",
	"tenías" : "tenía",
	"tendría" : "tendrías",
	"tendrías" : "tendría",
	# poder
	"podrás" : "podré",
	"podré" : "podrás",
	"puedo" : "puedes",
	"puedes" : "puedo",
	"pudé" : "pudiste",
	"pudiste" : "pudé",
	"podía" : "podías",
	"podías" : "podía",
	"podría" : "podrías",
	"podrías" : "podría",
	#cancelar
	"cancelaré" : "cancelarás",
	"cancelarás" : "cancelaré",
	"cancelo" : "cancelas",
	"cancelas" : "cancelo",
	"cancelé" : "cancelaste",
	"cancelaste" : "cancelé",
	"cancelabas" : "cancelaba",
	"cancelaba" : "cancelabas",
	"cancelaría" : "cancelarías",
	"cancelarías" : "cancelaría",
	#cambiar
	"cambiarás" : "cambiaré",
	"cambiaré" : "cambiarás",
	"cambio" : "cambias",
	"cambias" : "cambio",
	"cambié" : "cambiaste",
	"cambiaste" : "cambié",
	"cambiaba" : "cambiabas",
	"cambiabas" : "cambiaba",
	"cambiaría" : "cambiarías",
	"cambiarías" : "cambiaría",
	#limpiar
	"limpiarás" : "limpiaré",
	"limpiaré" : "limpiarás",
	"limpio" : "limpias",
	"limpias" : "limpio",
	"limpié" : "limpiaste",
	"limpiaste" : "limpié",
	"limpiaba" : "limpiabas",
	"limpiabas" : "limpiaba",
	"limpiaría" : "limpiarías",
	"limpiarías" : "limpiaría",
	#peinar
	"peinaré" : "peinarás",
	"peinarás" : "peinaré",
	"peino" : "peinas",
	"peinas" : "peino",
	"peiné" : "peinaste",
	"peinaste" : "peiné",
	"peinabas" : "peinaba",
	"peinaba" : "peinabas",
	"peinaría" : "peinarías",
	"peinarías" : "peinaría",
	#quejar
	"quejaré" : "quejarás",
	"quejarás" : "quejaré",
	"quejo" : "quejas",
	"quejas" : "quejo",
	"quejé" : "quejaste",
	"quejaste" : "quejé",
	"quejabas" : "quejaba",
	"quejaba" : "quejabas",
	"quejaría" : "quejarías",
	"quejarías" : "quejaría",
	#contar
	"contaré" : "contarás",
	"contarás" : "contaré",
	"cuento" : "cuentas",
	"cuentas" : "cuento",
	"conté" : "contaste",
	"contaste" : "conté",
	"contabas" : "contaba",
	"contaba" : "contabas",
	"contaría" : "contarías",
	"contarías" : "contaría",
	#cortar
	"cortaré" : "cortarás",
	"cortarás" : "cortaré",
	"corto" : "cortas",
	"cortas" : "corto",
	"corté" : "cortaste",
	"cortaste" : "corté",
	"cortaba" : "cortabas",
	"cortabas" : "cortaba",
	"cortaría" : "cortarías",
	"cortarías" : "cortaría",
	#bailar
	"bailaré" : "bailarás",
	"bailarás" : "bailaré",
	"bailo" : "bailas",
	"bailas" : "bailo",
	"bailé" : "bailaste",
	"bailaste" : "bailé",
	"bailaba" : "bailabas",
	"bailabas" : "bailaba",
	"bailaría" : "bailarías",
	"bailarías" : "bailaría",
	#dibujar
	"dibujaré" : "dibujarás",
	"dibujarás" : "dibujaré",
	"dibujo" : "dibujas",
	"dibujas" : "dibujo",
	"dibujé" : "dibujaste",
	"dibujaste" : "dibujé",
	"dibujaba" : "dibujabas",
	"dibujabas" : "dibujaba",
	"dibujaría" : "dibujarías",
	"dibujarías" : "dibujaría",
	#beber
	"beberé" : "beberás",
	"beberás" : "beberé",
	"bebo" : "bebes",
	"bebes" : "bebo",
	"bebí" : "bebiste",
	"bebiste" : "bebí",
	"bebía" : "bebías",
	"bebías" : "bebía",
	"bebería" : "beberías",
	"beberías" : "bebería",
	#conducir
	"conduciré" : "conducirás",
	"conducirás" : "conduciré",
	"conduzco" : "conduces",
	"conduces" : "conduzco",
	"conducí" : "conduciste",
	"conduciste" : "conducí",
	"conducíá" : "conducíás",
	"conducíás" : "conducía",
	"conduciría" : "conducirías",
	"conducirías" : "conduciría",
	#comer
	"comeré" : "comerás",
	"comerás" : "comeré",
	"como" : "comes",
	"comes" : "como",
	"comí" : "comiste",
	"comiste" : "comí",
	"comía" : "comías",
	"comías" : "comía",
	"comería" : "comerías",
	"comerías" : "comería",
	#explicar
	"explicaré" : "explicarás",
	"explicarás" : "explicaré",
	"explico" : "explicas",
	"explicas" : "explico",
	"expliqué" : "explicaste",
	"explicaste" : "expliqué",
	"explicabas" : "explicaba",
	"explicaba" : "explicabas",
	"explicaría" : "explicarías",
	"explicarías" : "explicaría",
	#caer
	"caeré" : "caerás",
	"caerás" : "caeré",
	"caigo" : "caes",
	"caes" : "caigo",
	"caí" : "caiste",
	"caiste" : "caí",
	"caía" : "caías",
	"caías" : "caía",
	"caerías" : "caería",
	"caería" : "caerías",
	#encontrar
	"encontraré" : "encontrarás",
	"encontrarás" : "encontraré",
	"encuentro" : "encuentras",
	"encuentras" : "encuentro",
	"encontré" : "encontraste",
	"encontraste" : "encontré",
	"encontraba" : "encontrabas",
	"encontrabas" : "encontraba",
	"encontraría" : "encontrarías",
	"encontrarías" : "encontraría",
	#volar
	"volaré" : "volarás",
	"volarás" : "volaré",
	"vuelo" : "vuelas",
	"vuelas" : "vuelo",
	"volé" : "volaste",
	"volaste" : "volé",
	"volaba" : "volabas",
	"volabas" : "volaba",
	"volaría" : "volarías",
	"volarías" : "volaría",
	#olvidar
	"olvidarás" : "olvidaré",
	"olvidaré" : "olvidarás",
	"olvido" : "olvidas",
	"olvidas" : "olvido",
	"olvidé" : "olvidaste",
	"olvidaste" : "olvidé",
	"olvidaba" : "olvidabas",
	"olvidabas" : "olvidaba",
	"olvidaría" : "olvidarías",
	"olvidarías" : "olvidaría",
	#dar
	"darás" : "daré",
	"daré" : "darás",
	"doy" : "das",
	"das" : "doy",
	"di" : "diste",
	"diste" : "di",
	"daba" : "dabas",
	"dabas" : "daba",
	"daría" : "darías",
	"darías" : "daría",
	#ir
	"ire" : "iras",
	"iras" : "ire",
	"voy" : "vas",
	"vas" : "voy",
	"fui" : "fuiste",
	"fuiste" : "fui",
	"iba" : "ibas",
	"ibas" : "iba",
	"iría" : "irías",
	"irías" : "iría",
	#oir
	"oiré" : "oirás",
	"oirás" : "oiré",
	"oigo" : "oyes",
	"oyes" : "oigo",
	"oí" : "oíste",
	"oíste" : "oí",
	"oía" : "oías",
	"oías" :"oía",
	"oiría" : "oirías",
	"oirías" : "oiría",
	# herir
	"heriré" : "herirás",
	"herirás" : "heriré",
	"hiero" : "hieres",
	"hieres" : "hiero",
	"herí" : "heriste",
	"heriste" : "herí",
	"herías" : "hería",
	"hería" : "herías",
	"herirías" : "heriría",
	"heriría" : "herirías",
	# conocer
	"conoceré" : "conocerás",
	"conocerás" : "conoceré",
	"conozco" : "conoces",
	"conoeces" : "conozco",
	"conocí" : "conociste",
	"conociste" : "conocí",
	"conocía" : "conocías",
	"conocías" : "conocía",
	"conocería" : "conocerías",
	"conocerías" : "conocería", 
	# aprender
	"aprenderé" : "aprenderás",
	"aprenderás" : "aprenderé",
	"aprendo" : "aprendes",
	"aprendes" : "aprendo",
	"aprendí" : "aprendiste",
	"aprendiste" : "aprendí",
	"aprendía" : "aprendías",
	"aprendías": "aprendía",
	"aprendería" : "aprenderías",
	"aprenderías" : "aprendería",
	# salir 
	"saldré" : "saldriás",
	"saldriás" : "saldré",
	"salgo" : "sales",
	"sales" : "salgo",
	"salí" : "saliste",
	"saliste" : "salí",
	"salía" : "salías",
	"salías" : "salía",
	"saldría" : "saldrías",
	"saldrías" : "saldría",
	# abandonar
	"abandonaré" : "abandonarás",
	"abandonarás" : "abandonaré",
	"abandono" : "abandonas",
	"abandonas" : "abandono",
	"abandoné" : "abandonaste",
	"abandonaste" : "abandoné",
	"abandonaba" : " abandonabas",
	"abandonabas" : "abandonaba",
	"abandonaría" : "abandonarías",
	"abandonarías" : "abandonaría",
	# escuchar
	"escucharé" : "escucharás",
	"escucharás" : "escucharé",
	"escucho" : "escuchas",
	"escuchas" : "escucho",
	"escuché" : "escuchaste",
	"escuchaste" : "escuché",
	"escuchaba" : "escuchabas",
	"escuchabas" : "escuchaba",
	"escucharía" : "escucharías",
	"escucharías" : "escucharía",
	# vivir
	"viviré" : "vivirás",
	"vivirás" : "viviré",
	"vivo" : "vives",
	"vives" : "vivo",
	"viví" : "viviste",
	"viviste" : "viví",
	"vivía" : "vivías",
	"vivías" : "vivía",
	"viviría" : "vivirías",
	"vivirías" : "viviría",
	# mirar
	"miraré" : "mirarás",
	"mirarás" : "miraré",
	"miro" : "miras",
	"miras" : "miro",
	"miré" : "miraste",
	"miraste" : "miré",
	"miraba" : "mirabas",
	"mirabas" : "miraba",
	"miraría" : "mirarías",
	"mirarías" : "miraría",
	# perder
	"perderé" : "perderás",
	"perderás" : "perderé",
	"pierdo" : "pierdes",
	"pierdes" : "pierdo",
	"perdí" : "perdiste",
	"perdiste" : "perdí",
	"perdía" :"perdías",
	"perdías" : "perdía",
	"perdería" : "perderías",
	"perderías" : "perdería",
	# hacer
	"haré" : "harás",
	"harás" : "haré",
	"hago" : "haces",
	"haces" : "hago",
	"hice" : "hiciste",
	"hiciste" : "hice", 
	"hacía" : "hacías",
	"hacías" : "hacía",
	"haría" : "harías",
	"harías" : "haría",
	# fabricar
	"fabricaré" : "fabricarás",
	"fabricarás" : "fabricaré",
	"fabrico" : "fabricas",
	"fabricas" : "fabrico",
	"fabriqué" : "fabricaste",
	"fabricaste" : "fabriqué",
	"fabricaba" : "fabricabas",
	"fabricabas" : "fabricaba",
	"fabricaría" : "fabricarías",
	"fabricarías" : "fabricaría",
	# necesitar
	"necesitaré" : "necesitarás",
	"necesitarás" : "necesitaré",
	"necesito" : "necesitas",
	"necesitas" : "necesito",
	"necesité" : "necesitaste",
	"necesitaste" : "necesité",
	"necesitaba" : "necesitabas",
	"necesitabas" : "necesitaba",
	"necesitaría" : "necesitarías",
	"necesitarías" : "necesitaría",
	# abrir
	"abriré" : "abrirás",
	"abrirás" : "abriré",
	"abro" : "abres",
	"abres" : "abro",
	"abrí" : "abriste",
	"abriste" : "abrí",
	"abría" : "abrías",
	"abrías" : "abría",
	"abriría" : "abrirías",
	"abrirías" : "abriría",
	# cerrar
	"cerraré" : "cerrarás",
	"cerrarás" : "cerraré",
	"cierro" : "cierras",
	"cierras" : "cierro",
	"cerré" : "cerraste",
	"cerraste" : "cerré",
	"cerraba" : "cerrabas",
	"cerrabas" : "cerraba",
	"cerraría" : "cerrarías",
	"cerrarías" : "cerraría",
	# organizar
	"organizaré" : "organizarás",
	"organizarás" : "organizaré",
	"organizo" : "organizas",
	"organizas" : "organizo",
	"organicé" : "organizaste",
	"organizaste" : "organicé",
	"organizaba" : "organizabas",
	"organizabas" : "organizaba",
	"organizaría" : "organizarías",
	"organizarías" : "organizaría",
	# pegar
	"pegaré" : "pegarás",
	"pegarás" : "pegaré",
	"pego" : "pegas",
	"pegas" : "pego",
	"pegué" : "pegaste",
	"pegaste" : "pegué",
	"pegaba" : "pegabas",
	"pegabas" : "pegaba",
	"pegaría" : "pegarías",
	"pegarías" : "pegaría",
	# jugar
	"jugaré" : "jugarás",
	"jugarás" : "jugaré",
	"juego" : "juegas",
	"juegas" : "juego",
	"jugué" : "jugasté",
	"jugasté" : "jugué",
	"jugaba" : "jugabas",
	"jugabas" : "jugaba",
	"jugaría" : "jugarías",
	"jugarías" : "jugaría",
	# poner
	"pondré" : "pondrás",
	"pondrás" : "pondré",
	"pongo" : "pones",
	"pones" : "pongo",
	"puse" : "pusiste",
	"pusiste" : "puse",
	"ponía" : "ponías",
	"ponías" : "ponía",
	"pondría" : "pondrías",
	"pondrías" : "pondría",
	# leer
	"leeré" : "leerás",
	"leerás" : "leeré",
	"leo" : "lees",
	"lees" : "leo",
	"leí" : "leiste",
	"leiste" : "leí",
	"leía" : "leías",
	"leías" : "leía",
	"leería" : "leerías",
	"leerías" : "leería",
	# llamar
	"llamaré" : "llamarás",
	"llamarás" : "llamaré",
	"llamo" : "llamas",
	"llamas" : "llamo",
	"llamé" : "llamaste",
	"llamaste" : "llamé",
	"llamaba" : "llamabas",
	"llamabas" : "llamaba",
	"llamaría" : "llamarías",
	"llamarías" : "llamaría",
	# contestar
	"contestaré" : "contestarás",
	"contestarás" : "contestaré",
	"contesto" : "contestas",
	"contestas" : "contesto",
	"contesté" : "contestaste",
	"contestaste" : "contesté",
	"contestaba" : "contestabas",
	"contestabas" : "contestaba",
	"contestaría" : "contestarías",
	"contestarías" : "contestarías",
	# correr
	"correré" : "correrás",
	"correrás" : "correré",
	"corro" : "corres",
	"corres" : "corro",
	"corrí" : "corrias",
	"corrias" : "corrí",
	"corría" : "corrías",
	"corrías" : "corría",
	"correría" : "correrías",
	"correrías" : "correría",
	# decir
	"diré" : "dirás",
	"dirás" : "diré",
	"digo" : "dices",
	"dices" : "digo",
	"dije" : "dijiste",
	"dijiste" : "dije",
	"decías" : "decía",
	"decía" : "decías",
	"diría" :"dirías",
	"dirías" : "diría",
	# ver
	"veré" : "verás",
	"verás" : "veré",
	"veo" : "ves",
	"ves" : "veo",
	"ví" : "viste",
	"viste" : "ví",
	"veía" : "veías",
	"veías" : "veía",
	"vería" : "verías",
	"verías" : "vería",
	# vender
	"venderé" : "venderás",
	"venderás" : "venderé",
	"vendo" : "vendes",
	"vendes" : "vendo",
	"vendí" : "vendiste",
	"vendiste" :"vendí",
	"vendía" : "vendías",
	"vendías" : "vendía",
	"vendería" : "venderías",
	"venderías" : "vendería",
	# enviar
	"enviaré" : "enviarás",
	"enviarás" : "enviaré",
	"envio" : "envias",
	"envias" : "envias",
	"envié" : "enviaste",
	"enviaste" : "envié",
	"enviaba" : "enviabas",
	"enviabas" : "enviaba",
	"enviaría" : "enviarías",
	"enviarías" : "enviaría",
	# firmar
	"firmaré" : "firmarás",
	"firmarás" : "firmaré",
	"firmo" : "firmas",
	"firmas" : "firmo",
	"firmé" : "firmaste",
	"firmaste" : "firmé",
	"firmaba" : "firmabas",
	"firmabas" : "firmaba",
	"firmaría" : "firmarías",
	"firmarías" : "firmaría",
	# grabar
	"grabaré" : "grabarás",
	"grabarás" : "grabaré",
	"grabo" : "grabas",
	"grabas" : "grabo",
	"grabé" : "grabaste",
	"grabaste" : "grabé",
	"grababa" : "grababas",
	"grababas" : "grababa",
	"grabaría" : "grabarías",
	"grabarías" : "grabaría",
	# cantar
	"cantaré" : "cantarás",
	"cantarás" : "cantaré",
	"canto" : "cantas",
	"cantas" : "canto",
	"canté" : "cantaste",
	"cantaste" : "canté",
	"cantaba" : "cantabas",
	"cantabas" : "cantaba",
	"cantaría" : "cantarías",
	"cantarías" : "cantaría",
	# sentar
	"sentaré" : "sentarás",
	"sentarás" : "sentaré",
	"siento" : "sientas",
	"sientas" : "siento",
	"senté" : "sentataste",
	"sentataste" : "senté",
	"sentabas" : "sentaba",
	"sentaba" : "sentabas",
	"sentaría" : "sentarías",
	"sentarías" : "sentaría",
	# sentir
	"sentiré" : "sentirás",
	"sentirás" : "sentiré",
	"siento" : "sientes",
	"sientes" : "siento",
	"sentí" : "sentiste",
	"sentiste" : "sentí",
	"sentía" : "sentías",
	"sentías" : "sentía",
	"sentiría" : "sentirías",
	"sentirías" : "sentiría", 
	# amar
	"amaré" : "amarás",
	"amarás" : "amaré",
	"amo" : "amas",
	"amas" : "amo",
	"amé" : "amaste",
	"amaste" : "amé",
	"amaba" : "amabas",
	"amabas" : "amaba",
	"amaría" : "amarías",
	"amarías" : "amaría",
	# mentir
	"mentirás" : "mentiré",
	"mentiré" : "mentirás",
	"miento" : "mientes",
	"mientes" : "miento",
	"mentí" : "mentiste",
	"mentiste" : "mentí",
	"mentía" : "mentías",
	"mentías" : "mentía",
	"mentiría" : "mentirías",
	"mentirías" : "mentiría",
	# dormir
	"dormiré" : "dormirás",
	"dormirás" : "dormiré",
	"duermo" : "duermes",
	"duermes" : "duermo",
	"dormí" : "dormiste",
	"dormiste" : "dormí",
	"dormía" : "dormías",
	"dormías" : "dormía",
	"dormiría" : "dormirías",
	"dormirías" : "dormiría",
	# fumar
	"furmaré" : "furmarás",
	"furmarás" : "furmaré",
	"fumo" : "fumas",
	"fumas" : "fumo",
	"fumé" : "fumaste",
	"fumaste" : "fumé",
	"fumaba" : "fumabas",
	"fumabas" : "fumaba",
	"fumaría" : "fumarías",
	"fumarías" : "fumaría",
	# conversar
	"conversaré" : "conversarás",
	"conversarás" : "conversaré",
	"converso" : "conversas",
	"conversas" : "converso",
	"conversé" : "conversaste",
	"conversaste" : "conversé",
	"conversaba" : "conversabas",
	"conversabas" : "conversaba",
	"conversaría" : "conversarías",
	"conversarías" : "conversaría",
	# deletrear
	"deletrearé" : "deletrearás",
	"deletrearás" : "deletrearé",
	"deletreo" : "deletreas",
	"deletreas" : "deletreo",
	"deletrié" : "deletreaste",
	"deletreaste" : "deletrié",
	"deletreaba" : "deletreabas",
	"deletreabas" : "deletreabas",
	"deletrearía" : "deletrearías",
	"deletrearías" : "deletrearía",
	# matar
	"mataré" : "matarás",
	"matarás" : "mataré",
	"mato" : "matas",
	"matas" : "mato",
	"maté" : "mataste",
	"mataste" : "maté",
	"mataba" : "matabas",
	"matabas" : "mataba",
	"mataría" : "matarías",
	"matarías" : "mataría",
	# enfermar
	"enfermaré" : "enfermarás",
	"enfermarás" : "enfermaré",
	"enfermo" : "enfermas",
	"enfermas" : "enfermo",
	"enfermé" : "enfermaste",
	"enfermaste" : "enfermé",
	"enfermaba" : "enfermabas",
	"enfermabas" : "enfermaba",
	"enfermaría" : "enfermarías",
	"enfermarías" : "enfermaría",
	# golpear
	"golpearás" : "golpearé",
	"golpearé" : "golpearás",
	"golpeo" : "golpeas",
	"golpeas" : "golpeo",
	"golpié" : "golpiaste",
	"golpiaste" : "golpié",
	"golpeaba" : "golpeabas",
	"golpeabas" : "golpeaba",
	"golpearía" : "golpearías",
	"golpearías" : "golpearía",
	# gastar
	"gastaré" : "gastarás",
	"gastarás" : "gastaré",
	"gasto" : "gastas",
	"gastas" : "gasto",
	"gasté" : "gastaste",
	"gastaste" : "gaste",
	"gastaba" : "gastabas",
	"gastabas" : "gastaba",
	"gastaría" : "gastarías",
	"gastarías" : "gastaría",
	# gustar
	"gustaré" : "gustarás",
	"gustarás" : "gustaré",
	"gusto" : "gustas",
	"gustas" : "gusto",
	"gusté" : "gustaste",
	"gustaste" : "gusté",
	"gustaba" : "gustabas",
	"gustabas" : "gustaba",
	"gustaría" : "gustarías",
	"gustarías" : "gustaría",
	# mantener
	"mantendré" : "mantendrá",
	"mantendrá" : "mantendré",
	"mantengo" : "mantienes",
	"mantienes" : "mantengo",
	"mantuve" : "mantuviste",
	"mantuviste" : "mantuve",
	"mantenía" : "mantenías",
	"mantenías" : "mantenía",
	"mantendría" : "mantendrías",
	"mantendrías" : "mantendría",
	# comenzar 
	"comenzaré" : "comenzarás",
	"comenzarás" : "comenzaré",
	"comienzo" : "comienzas",
	"comienzas" : "comienzo",
	"comencé" : "comenzaste",
	"comenzaste" : "comencé",
	"comenzaba" : "comenzabas",
	"comenzabas" : "comenzaba",
	"comenzaría" : "comenzarías",
	"comenzarías" : "comenzaría",
	# iniciar
	"iniciaré" : "iniciarás",
	"iniciarás" : "iniciaré",
	"inicio" : "inicias",
	"inicias" : "inicio",
	"inicié" : "iniciaste",
	"iniciaste" : "inicié",
	"iniciaba" : "iniciabas",
	"iniciabas" : "iniciaba",
	"iniciaría" : "iniciarías",
	"iniciarías" : "iniciaría",
	# estudiar
	"estudiaré" : "estudiarás",
	"estudiarás" : "estudiaré",
	"estudio" : "estudias",
	"estudias" : "estudio",
	"estudié" : "estudiaste",
	"estudiaste" : "estudié",
	"estudiaba" : "estudiabas",
	"estudiabas" : "estudiaba",
	"estudiaría" : "estudiarías",
	"estudiarías" : "estudiaría",
	# triunfar
	"triunfaré" : "triunfarás",
	"triunfarás" : "triunfaré",
	"triunfo" : "triunfas",
	"triunfas" : "triunfo",
	"triunfé" : "triunfaste",
	"triunfaste" : "triunfé",
	"triunfaba" : "triunfabas",
	"triunfabas" : "triunfaba",
	"triunfaría" : "triunfarías",
	"triunfarías" : "triunfaría",
	# ganar
	"ganaré" : "ganarás",
	"ganarás" : "ganaré",
	"gano" : "ganas",
	"ganas" : "gano",
	"gané" : "ganaste",
	"ganaste" : "gané",
	"ganabas" : "ganaba",
	"ganaba" : "ganabas",
	"ganaría" : "ganarías",
	"ganarías" : "ganaría",
	# nadar
	"nadaré" : "nadarás",
	"nadarás" : "nadaré",
	"nado" : "nadas",
	"nadas" : "nado",
	"nadé" : "nadaste",
	"nadaste" : "nadé",
	"nadaba" : "nadabas",
	"nadabas" : "nadaba",
	"nadaría" : "nadarías",
	"nadarías" : "nadaría",
	# llevar
	"llevaré" : "llevarás",
	"llevarás" : "llevaré",
	"llevo" : "llevas",
	"llevas" : "llevo",
	"llevé" :"llevaste",
	"llevaste" : "llevé",
	"llevaba" : "llevabas",
	"llevabas" : "llevaba",
	"llevaría" : "llevarías",
	"llevarías" : "llevaría",
	# hablar
	"hablaré" : "hablarás",
	"hablarás" : "hablaré",
	"hablo" : "hablas",
	"hablas" : "hablo",
	"hablé" : "hablaste",
	"hablaste" : "hablé",
	"hablaba" : "hablabas",
	"hablabas" : "hablaba",
	"hablaría" : "hablarías",
	"hablarías" : "hablaría",
	# enseñar
	"enseñaré" : "enseñarás",
	"enseñarás" : "enseñaré",
	"enseño" : "enseñas",
	"enseñas" : "enseño",
	"enseñé" : "enseñaste",
	"enseñaste" : "enseñé",
	"enseñaba" : "enseñabas",
	"enseñabas" : "enseñaba",
	"enseñaría" : "enseñarías",
	"enseñarías" : "enseñaría",
	# pensar
	"pensaré" : "pensarás",
	"pensarás" : "pensaré",
	"pienso" : "piensas",
	"piensas" : "pienso",
	"pensé" : "pensaste",
	"pensaste" : "pensé",
	"pensaba" : "pensabas",
	"pensabas" : "pensaba",
	"pensaría" : "pensarías",
	"pensarías" : "pensaría",
	# traducir
	"traducirás" : "traduciré",
	"traduciré" : "traducirás",
	"traduzco" : "traduces",
	"traduces" : "traduzco",
	"traduje" : "tradujiste",
	"tradujiste" : "traduje",
	"treducía" : "traducías",
	"traducías" : "traducía",
	"traduciría" : "traducirías",
	"traducirías" : "traduciría",
	# viajar
	"viajarás" : "viajaré",
	"viajaré" : "viajarás",
	"viajo" : "viajas",
	"viajas" : "viajo",
	"viajé" : "viajaste",
	"viajaste" : "viajé",
	"viajaba" : "viajabas",
	"viajabas" : "viajaba",
	"viajaría" : "viajarías",
	"viajarías" : "viajaría",
	# probar 
	"probaré" : "probarás",
	"probarás" : "probaré",
	"pruebo" : "pruebas",
	"pruebas" : "pruebo",
	"probé" : "probaste",
	"probaste" : "probé",
	"probaba" : "probabas",
	"probabas" : "probaba",
	"probaría" : "probarías",
	"probarías" : "probaría",
	# intentar
	"intentarás" : "intentarés",
	"intentarés" : "intentarás",
	"intento" : "intentas",
	"intentas" : "intento",
	"intenté" : "intetaste",
	"intetaste" : "intenté",
	"intentaba" : "intentabas",
	"intentabas" : "intentaba",
	"intentaría" : "intentarías",
	"intentarías" : "intentaría",
	# apagar
	"apagarás" : "apagaré",
	"apagaré" : "apagarás",
	"apago" : "apagas",
	"apagas" : "apago",
	"apagué" : "apagaste",
	"apagaste" : "apagué",
	"apagaba" : "apagabas",
	"apagabas" : "apagaba",
	"apagaría" : "apagarías",
	"apagarías" : "apagaría",
	# encender
	"encenderé" : "encenderás",
	"encenderás" : "encenderé",
	"enciendo" : "enciendes",
	"enciendes" : "enciendo",
	"encendí" : "encendiste",
	"encendiste" : "encendí",
	"encendía" : "encendías",
	"encendías" : "encendía",
	"encendería" : "encenderías",
	"encenderías" : "encendería",
	# comprender
	"comprenderé" : "comprenderás",
	"comprenderás" : "comprenderé",
	"comprendo" : "comprendes",
	"comprendes" : "comprendo",
	"comprendí" : "comprendiste",
	"comprendiste" : "comprendí",
	"comprendía" : "comprendías",
	"comprendías": "comprendía",
	"comprendería" : "comprenderías",
	"comprenderías" : "comprendería",
	# usar
	"usaré" : "usarás",
	"usarás" : "usaré",
	"uso" : "usas",
	"usas" : "uso",
	"usé" : "usaste",
	"usaste" : "usé",
	"usaba" : "usabas",
	"usabas" : "usaba",
	"usaría" : "usarías",
	"usarías" : "usaría",
	# utilizar
	"utilizaré" : "utilizarás",
	"utilizarás" : "utilizaré",
	"utilizo" : "utilizas",
	"utilizas" : "utilizo",
	"utilicé" : "utilizaste",
	"utilizaste" : "utilicé",
	"utilizaba" : "utilizabas",
	"utilizabas" : "utilizaba",
	"utilizaría" : "utilizarías",
	"utilizarías" : "utilizaría",
	# esperar
	"esperaré" : "esperarás",
	"esperarás" : "esperaré",
	"espero" : "esperas",
	"esperas" : "espero",
	"esperé" : "esperaste",
	"esperaste" : "esperé",
	"esperaba" : "esperabas",
	"esperabas" : "esperaba",
	"esperaría" : "esperarías",
	"esperarías" : "esperaría",
	# despertar
	"despertaré" : "despertarás",
	"despertarás" : "despertaré",
	"despierto" : "despiertas",
	"despiertas" : "despierto",
	"desperté" : "despertaste",
	"despertaste" : "desperté",
	"despertaba" : "despertabas",
	"despertabas" : "despertaba",
	"despertaría" : "despertarías",
	"despertarías" : "despertaría",
	# querer
	"querré" : "querrás",
	"querrás" : "querré",
	"quiero" : "quieres",
	"quieres" : "quiero",
	"quise" : "quisiste",
	"quisiste" : "quise",
	"quería" : "querías",
	"querías" : "quería",
	"querría" : "querrías",
	"querrías" : "querría",
	# patear
	"patearé" : "patearás",
	"patearás" : "patearé",
	"pateo" : "pateas",
	"pateas" : "pateo",
	"patié" : "patiaste",
	"patiaste" : "patié",
	"pateaba" : "pateabas",
	"pateabas" : "pateaba",
	"patearía" : "patearías",
	"patearías" : "patearía",
	# destruir
	"destruiré" : "destruirás",
	"destruirás" : "destruiré",
	"destruyo" : "destruyes",
	"destruyes" : "destruyo",
	"destruí" : "destruiste",
	"destruiste" : "destruí",
	"destruía" : "destruías",
	"destruías" : "destruía",
	"destruiría" : "destruirías",
	"destruirías" : "destruiría",
	# solucionar
	"solucionaré" : "solucionarás",
	"solucionarás" : "solucionaré",
	"soluciono" : "solucionas",
	"solucionas" : "soluciono",
	"solucioné" : "solucionaste",
	"solucionaste" : "solucioné",
	"solucionaba" : "solucionabas",
	"solucionabas" : "solucionaba",
	"solucionaría" : "solucionarías",
	"solucionarías" : "solucionaría",
	# resolver
	"resolverás" : "resolveré",
	"resolveré" : "resolverás",
	"resuelvo" : "resuelves",
	"resuelves" : "resuelvo",
	"resolví" : "resolviste",
	"resolviste" : "resolví",
	"resolvía" : "resolvías",
	"resolvías" : "resolvía",
	"resolvería" : "resolverías",
	"resolverías" : "resolvería",
	# diseñar
	"diseñaré" : "diseñarás",
	"diseñarás" : "diseñaré",
	"diseño" : "diseñas",
	"diseñas" : "diseño",
	"diseñé" : "diseñasté",
	"diseñasté" : "diseñé",
	"diseñaba" : "diseñabas",
	"diseñabas" : "diseñaba",
	"diseñaría" : "diseñarías",
	"diseñarías" : "diseñaría",
	# inventar
	"inventaré" : "inventarás",
	"inventarás" : "inventaré",
	"invento" : "inventas",
	"inventas" : "invento",
	"inventé" : "inventaste",
	"inventaste" : "inventé", 
	"inventaba" : "inventabas",
	"inventabas" : "inventaba",
	"inventaría" : "inventarías",
	"inventarías" : "inventaría",
	# programar
	"programaré" : "programarás",
	"programarás" : "programaré",
	"programo" : "programas",
	"programas" : "programo",
	"programé" : "programaste",
	"programaste" : "programé",
	"programaba" : "programabas",
	"programabas" : "programaba",
	"programaría" : "programarías",
	"programarías" : "programaría",
	# desear
	"desearé" : "desearás",
	"desearás" : "desearé",
	"deseo" : "deseas",
	"deseas" : "deseo",
	"desée" : "deseaste",
	"deseaste" : "desée",
	"deseaba" : "deseabas",
	"deseabas" : "deseaba",
	"desearía" : "desearías",
	"desearías" : "desearía",
	# reparar
	"repararé" : "repararás",
	"repararás" : "repararé",
	"reparo" : "reparas",
	"reparas" : "reparo",
	"reparé" : "reparaste",
	"reparaste" : "reparé",
	"reparaba" : "reparabas",
	"reparabas" : "reparaba",
	"repararía" : "repararías",
	"repararías" : "repararía",
	# vencer
	"venceré" : "vencerás",
	"vencerás" : "venceré",
	"venzo" : "vences",
	"vences" : "venzo",
	"vencí" : "venciste",
	"venciste" : "vencí",
	"vencía" : "vencías",
	"vencías" : "vencía",
	"vencería" : "vencerías",
	"vencerías" : "vencería",
	# arreglar
	"arreglarás" : "arreglaré",
	"arreglaré" : "arreglarás",
	"arreglo" : "arreglas",
	"arreglas" : "arreglo",
	"arreglé" : "arreglaste",
	"arreglaste" : "arreglé",
	"arreglaba" : "arreglabas",
	"arreglabas" : "arreglaba",
	"arreglaría" : "arreglarías",
	"arreglarías" : "arreglaría",
	# dañar
	"dañarás" : "dañaré",
	"dañaré" : "dañarás",
	"daño" : "dañas",
	"dañas" : "daño",
	"dañé" : "dañaste",
	"dañaste" : "dañé",
	"dañaba" : "dañabas",
	"dañabas" : "dañaba",
	"dañaría" : "dañarías",
	"dañarías" : "dañaría",
	# avergonzar
	"avergonzarás" : "avergonzaré",
	"avergonzaré" : "avergonzarás",
	"avergüenzo" : "avergüenzas",
	"avergüenzas" : "avergüenzo",
	"avergoncé" : "avergonzaste",
	"avergonzaste" : "avergoncé",
	"avergonzaba" : "avergonzabas",
	"avergonzabas" : "avergonzaba", 
	"avergonzaría" : "avergonzarías",
	"avergonzarías" : "avergonzaría",
	# disfrutar
	"disfrutaré" : "disfrutarás",
	"disfrutarás" : "disfrutaré",
	"disfruto" : "disfrutas",
	"disfrutas" : "disfruto",
	"disfruté" : "disfrutaste",
	"disfrutaste" : "disfruté",
	"disfrutaba" : "disfrutabas",
	"disfrutabas" : "disfrutaba",
	"disfrutaría" : "disfrutarías",
	"disfrutarías" : "disfrutaría",
	# gozar
	"gozaré" : "gozarás",
	"gozarás" : "gozaré",
	"gozo" : "gozas",
	"gozas" : "gozo",
	"gocé" : "gozaste",
	"gozaste" : "gocé",
	"gozaba" : "gozabas",
	"gozabas" : "gozaba",
	"gozaría" : "gozarías",
	"gozarías" : "gozaría",
	# estrellar
	"estrellaré" : "estrellarás",
	"estrellarás" : "estrellaré",
	"estrello" : "estrellas",
	"estrellas" : "estrello",
	"estrellé" : "estrellaste",
	"estrellaste" : "estrellé",
	"estrellaba" : "estrellabas",
	"estrellabas" : "estrellaba",
	"estrellaría" : "estrellarías",
	"estrellarías" : "estrellaría",
	# ridiculizar
	"ridiculizaré" : "ridiculizarás",
	"ridiculizarás" : "ridiculizaré",
	"ridiculizo" : "ridiculizas",
	"ridiculicé" : "ridiculizaste",
	"ridiculizaste" : "ridiculicé",
	"ridiculizaba" : "ridiculizabas",
	"ridiculizabas" : "ridiculizaba",
	"ridiculizaría" : "ridiculizarías",
	"ridiculizarías" : "ridiculizaría",
	# tocar
	"tocaré" : "tocarás",
	"tocarás" : "tocaré",
	"toco" : "tocas",
	"tocas" : "toco",
	"toqué" : "tocaste",
	"tocaste" : "toqué",
	"tocaba" : "tocabas",
	"tocabas" : "tocaba",
	"tocaría" : "tocarías",
	"tocarías" : "tocaría",
	# coger
	"cogeré" : "cogerás",
	"cogerás" : "cogeré",
	"cojo" : "coges",
	"coges" : "cojo",
	"cogí" : "cogiste",
	"cogiste" : "cogí",
	"cogía" : "cogías",
	"cogías" : "cogía",
	"cogería" : "cogerías",
	"cogerías" : "cogería",
	# recoger
	"recogeré" : "recogerás",
	"recogerás" : "recogeré",
	"recojo" : "recoges",
	"recoges" : "recojo",
	"recogí" : "recogiste",
	"recogiste" : "recogí",
	"recogía" : "recogías",
	"recogías" : "recogía",
	"recogería" : "recogerías",
	"recogerías" : "recogería",
	# reconocer
	"reconoceré" : "reconocerás",
	"reconocerás" : "reconoceré",
	"reconozco" : "reconoces",
	"reconoces" : "reconozco",
	"reconocí" : "reconociste",
	"reconociste" : "reconocí",
	"reconocía" : "reconocías",
	"reconocías" : "reconocía",
	"reconocería" : "reconocerías",
	"reconocerías" : "reconocería",
	# robar
	"robaré" : "robarás",
	"robarás" : "robaré",
	"robo" : "robas",
	"robas" : "robo",
	"robé" : "robaste",
	"robaste" : "robé",
	"robabas" : "robaba",
	"robaba" : "robabas",
	"robaría" : "robarías",
	"robarías" : "robaría",
	# tomar
	"tomaré" : "tomarás",
	"tomarás" : "tomaré",
	"tomo" : "tomas",
	"tomas" : "tomo",
	"tomé" : "tomaste",
	"tomaste" : "tomé",
	"tomaba" : "tomabas",
	"tomabas" : "tomaba",
	"tomaría" : "tomarías",
	"tomarías" : "tomaría",
	# saltar
	"saltarás" : "saltaré",
	"saltaré" : "saltarás",
	"salto" : "saltas",
	"saltas" : "salto",
	"salté" : "saltaste",
	"saltaste" : "salté",
	"salías" : "salía",
	"salía" : "salías",
	"saltaría" : "saltarías",
	"saltarías" : "saltaría",
	# alegrar
	"alegrarás" : "alegraré",
	"alegraré" : "alegrarás",
	"alegro" : "alegras",
	"alegras" : "alegro",
	"alegré" : "alegraste",
	"alegraste" : "alegré",
	"alegraba" : "alegrabas",
	"alegrabas" : "alegraba",
	"alegraría" : "alegrarías",
	"alegrarías" : "alegraría",
	# llorar
	"llorarás" : "lloraré",
	"lloraré" : "llorarás",
	"lloro" : "lloras",
	"lloras" : "lloro",
	"lloré" : "lloraste",
	"lloraste" : "lloré",
	"lloraba" : "llorabas",
	"llorabas" : "lloraba",
	"lloraría" : "llorarías",
	"llorarías" : "lloraría",
	# observar
	"observaré" : "observarás",
	"observarás" : "observaré",
	"observo" : "observas",
	"observas" : "observo",
	"observé" : "observaste",
	"observaste" : "observé",
	"observabas" : "observaba",
	"observaba" : "observabas",
	"observaría" : "observarías",
	"observarías" : "observaría",
	# trabajar
	"trabajarás" : "trabajaré",
	"trabajaré" : "trabajarás",
	"trabajo" : "trabajas",
	"trabajas" : "trabajo",
	"trabajé" : "trabajaste",
	"trabajaste" : "trabajé",
	"trabajabas" : "trabajaba",
	"trabajaba" : "trabajabas",
	"trabajaría" : "trabajarías",
	"trabajarías" : "trabajaría",
	# preocupar
	"preocuparás" : "preocuparé",
	"preocuparé" : "preocuparás",
	"preocupo" : "preocupas",
	"preocupas" : "preocupo",
	"preocupé" : "preocupaste",
	"preocupaste" : "preocupé",
	"preocupaba" : "preocupabas",
	"preocupabas" : "preocupaba",
	"preocuparía" : "preocuparías",
	"preocuparías" : "preocuparía",
	# escrbir
	"escribirás" : "escribiré",
	"escribiré" : "escribirás",
	"escribo" : "escribes",
	"escribes" : "escribo",
	"escribí" : "escribiste",
	"escribiste" : "escribí",
	"escribía" : "escribías",
	"escribías" : "escribía",
	"escribiría" : "escribirías",
	"escribirías" : "escribiría"
}

gPats = [
	[r'(Y|y)o necesito(.*)',
	["¿Por que tu necesitas %1?",
	"¿Eso realmente te ayuda a obtener %1?",
	"¿Estas seguro que necesitas %1?"]],

	[r'(¿)?Por que tu no ([^\?]*)\??',
	[ "¿Tu realmente crees que yo no %1?",
	"Tal vez algun dia yo %1.", #PREGUNTA
	"¿Tu realmente me quieres a mi para %1?"]],
	 
	[r'(¿)?(P|p)or que no puedo ([^\?]*)\??',
	[ "¿Crees que deberias ser capaz de %1?",
	"¿Si tu pudieras %1, Que harias?",
	"No lo se -- ¿Por que tu no puedes %1?",
	"¿Realmente lo has intentado?"]],

	[r'(Y|y)o no puedo(.*)',
	[ "¿Como sabes que no puedes %1?",
	"Sin embargo tu podrias %1 si tu lo intentas.",
	"¿Que haria falta para que usted pudiera %1?"]],

	[r'(Y|y)o soy(.*)',
	[ "¿Viniste a mi por que eres %1?",
	"¿Hace cuanto eres %1?",
	"¿Como te sientes siendo %1?"]],

	[r'(S|s)oy(.*)',#yo soy
	[ "¿Como te hace sentir ser %1?",
	"¿Disfrutas ser %1?",
	"¿Por que me cuentas que eres %1?",
	"¿Por que crees que eres %1?"]],

	[r'(¿)?(T|t)u eres ([^\?]*)\??',
	[ "¿Por que importa lo que sea %1?",
	"¿Te gustaria que no fuera %1?",
	"Pero piensas que soy %1.",]],

	[r'(¿)?(Q|q)ue es(.*)\??',
	[ "¿Por que lo preguntas?",
	"No tengo respuesta para eso, quizas Siri o Cortana si :P",
	"¿Ya buscaste en Google?"]],

	[r'(¿)?(C|c)omo es(.*)\??',
	[ "¿Como supones que es %1?",
	"Quizas tu puedas contestar a tu pregunta",
	"¿Por que me preguntas eso?"]],

	[r'(P|p)orque (.*)',
	[ "¿Esa es la razon?",
	"¿Que otras razones te vienen a la mente?",
	"¿Estas seguro que %1?",
	"Estoy de acuerdo"]],

	[r'(.*)perd(ó|o)n|perd(ó|o)name(.*)',
	[ "En muchos casos una disculpa no es suficiente.",
	"¿Prometes no volver a hacerlo?"]],

	[r'(H|h)ola(.*)',
	[ "¡Hola!, no sabes lo feliz que estoy de verte de nuevo :D",
	"Hola, ¿Como estas?",
	"Hola, ¿Como te sientes hoy?"]],

	[r'(y|Y)o creo(.*)',
	[ "¿Dudas %1?",
	"¿Realmente crees eso?",
	"No estoy de acuerdo"]],

	[r'(.*)amigo?s(.*)',
	[  "Hablame sobre tus amigos",
	"Cuando piensas en un amigo, ¿que viene a tu cabeza?",
	"¿Cuentame de tus amigos de infancia?"]],

	[r'(S|s)i',
	["Luces muy seguro",
	"Bueno",
	"¿Podrias decirme por que?"]],

	[r'(N|n)o',
	["Luces muy seguro",
	"Bueno",
	"¿Podrias decirme por que?"]],

	[r'(.*)computador(.*)',
	["¿Estas hablando acerca de mi?",
	"¿Te parece extraño hablar conmigo?",
	"¿Como te hace sentir hablar con computadores?",
	"¿Te sientes amenazado por las computadoras?"]],

	[r'(e|E)so es(.*)\?',
	[  "Crees que eso es %1?",
	"Tal vez es %1 -- Que piensas?",
	"Si fuera %1, Que harias?",
	"Bien podria ser %1."]],

	[r'(C|c)onoces a(.*)\??',
	[ "¿No podria asegurar que conozca a %1?",
	"Si claro, %1 es un gran programador",
	"Si claro, terrible programador",
	"¿Tu conoces a %1?"]],

	[r'(S|s)abes programar(.*)\??',
	['Dos veces World final',
	'La programacion es mi vida',
	'La FFT se me da bien',
	'Fefetealo che!', 
	'si, algunos pg\'s'
	]],

	[r'(E|e)s(.*)',
	[ "Tu pareces muy seguro.",
	"Si te digo que eso no es %1, ¿que sentirías?"]],

	[r'(P|p)odrias([^\?]*)\??',
	[ "¿Que te hace pensar que no podria %1?",
	"Si podria %1, ¿entonces que?",
	"¿Por que preguntas si puedo %1?"]],

	[r'(P|p)odria ([^\?]*)\??',
	["¿Quizas no quieres %1.",
	"¿Realmete crees que podrias %1?",
	"Si puedes %1, ¿por que no lo haces?"]],

	[r'(T|t)u eres(.*)',
	[ "¿Por que crees que soy %1?",
	"¿No te gusta que sea %1?",
	"Tambien quieres ser %1.",
	"¿Te ves reflejado en mi?"]],

	[r'(.*)eres(.*)',
	[ "¿Por que dices que soy %1?",
	"¿Por que piensas que soy %1?",
	"¿Estamos hablando de ti o de mi?"]],

	[r'(T|t)u (no)?(.*)',
	["¿Por que no %1?",
	"¿Realmente %1?",
	"Deberiamos hablar de ti, no de mi."]],

	[r'(Y|y)o (me)? siento(.*)',
	[  "Es bueno que te expreses, cuentame mas.",
	"¿Usualmente te sientes %1?",
	"¿Cuando te sientes %1?",
	"Cuando te sientes %1, ¿que haces?"]],

	[r'(Y|y)o tengo(.*)',
	[ "¿Por que dices que tienes %1?",
	"¿Realmente tienes %1?",
	"Ahora tu tienes %1, ¿que tendras despues?"]],

	[r'(p|P)odria(.*)',
	[ "¿Podrias explicar por que tu podrias %1?",
	"¿Por que podrias %1?",
	"¿Quien mas sabe que tu podrias %1?"]],

	[r'(H|h)ay(.*)',
	[ "¿Tu crees que hay %1?",
	"¡Es probable que exista!",
	"¿Te gustaria que hubiera %1?"]],

	[r'(M|m)i(.*)',
	[ "Ya veo tu %1.",
	"¿Por que dices que es tuyo?"]],

	[r'(P|p)or que(.*)',
	[ "¿Por que no me dices tu?",
	"¿Tu crees que %1?" ]],

	[r'(Y|y)o quiero(.*)',
	[ "¿Que harias si consigues %1?",
	"Por que lo quieres%1?",
	"Que harias si no consigues %1?",]],

	[r'(.*)(madre|mam(á|a))(.*)',
	[ "Dime más acerca de tu madre.",
	"¿Como es la relación con tu madre?",
	"¿Como te hace sentir tu madre?",
	"¿Amas a tu madre?",
	"¡Las buenas relaciones familiares son importantes!"]],

	[r'(.*)(padre|pap(á|a))(.*)',
	["Dime mas acerca de tu padre.",
	"¿Como es la relación con tu padre?",
	"¿Como te hace sentir tu padre?",
	"¿Amas a tu padre?",
	"¡Las buenas relaciones familiares son importantes!"]],

	[r'(.*)trauma(.*)',
	['Cuentame un poco mas.',
	'¿Hace cuanto que tienes este trauma?',
	'¿Es algo reciente?']],

	[r'(.*)niñez(.*)',
	[  "¿Tienes amigos de la niñez?",
	"¿Cual es tu mejor recuerdo de pequeño?",
	"¿Recuerdas algun sueño que tenias cuando eras pequeño?",
	"¿De niño se burlaban de ti?",
	"¿Crees que tus vivencias de niño fueron significativas?"]],

	[r'(.*)\?',
	["¿Por que preguntas eso?",
	"Por favor considera que podrias responder tu mismo la pregunta.",
	"Quizas ¿la respuesta esta en tu corazón?",
	"¿Por que me preguntas si sabes que no se la respuesta?",
	"Soy terapista, no adivina."]],

	[r'(S|s)alir',
	["Gracias por hablar conmigo!",
	"Adios, ten un gran día!",
	"Hasta pronto y no olvides disfrutar la vida que solo es una."
	"Gracias son $10.000, Ten un gran día!"]],

	[r'((J|j)aja(ja)*|(l|L)ol|LOL)(.*)',
	["¿Por que te ríes?",
	"¿Que te parece gracioso?",
	"¿Cual es el motivo de tu risa?",
	"¿Que dije que fuera gracioso?"]],

	[r'(.*)',
	["Por favor cuentame más.",
	"Cambiemos de tema, no quiero hablar de eso.",
	"¿Puedes contarme mas sobre eso?",
	"¿Por que dices que %1?",
	"Ya veo.",
	"Muy interesante.",
	"%1.",
	"OK, y eso ¿que te dice?",
	"Y eso ¿como te hace sentir?",
	"¿Como te sientes cuando dices eso?"]]
]

def begin_chat():
	#DATOS --> http://deixilabs.com/elizadata.js
	#      --> http://deixilabs.com/aliziadata.js
	print "\n\t\t\t\t  ELIZA\n"
	print "|"+"="*75+"|"
	print '|  Charla con ELIZA en español de lo que desees.'+(' '*27)+'|'
	print "|"+'='*75+"|"	
	print "\nELIZA:  Hola. ¿Como te sientes hoy?"
	s = ""
	terapista = Eliza()
	while s.lower() != 'salir':
		try:
			s = raw_input("TÚ:    ")
		except EOFError:
			s = "salir"
			print s
		while s[-1] in "!.": s = s[:-1]
		print "ELIZA:  "+terapista.respond(s)

if __name__ == "__main__":
	begin_chat()